const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const DESIGN_DIR = path.join(ROOT, "design");
const SECTIONS_DIR = path.join(DESIGN_DIR, "sections");
const PUBLIC_DESIGN = path.join(ROOT, "public", "design");

const STANDALONE = path.join(ROOT, "PetalFlow-Dashboard-standalone.html");
const STANDALONE_COPY = path.join(DESIGN_DIR, "PetalFlow-Dashboard-standalone.html");

function extractTemplate() {
  const source = fs.existsSync(STANDALONE) ? STANDALONE : STANDALONE_COPY;
  const html = fs.readFileSync(source, "utf8");
  const start = html.indexOf('<script type="__bundler/template">');
  const end = html.indexOf("</script>", start);
  if (start === -1) throw new Error("Bundler template not found in standalone HTML");
  const inner = html.slice(start + '<script type="__bundler/template">'.length, end).trim();
  return JSON.parse(inner);
}

/** Minimal processing — keep markup visually identical to the source file */
function processHtmlIdentical(html) {
  let result = html
    .replace(/src="faaa21af-e87d-4492-a9a8-c8eda408b1b7"/g, 'src="/design/faaa21af-e87d-4492-a9a8-c8eda408b1b7.png"')
    .replace(/<script src="50ef2e23-41f2-4bcb-ad3c-32cba783a2fb"><\/script>/g, "");

  const navItems = [
    ["Today", "/dashboard"],
    ["Timeline", "/timeline"],
    ["Garden", "/garden"],
    ["Search", "/search"],
    ["Collections", "/collections"],
    ["Inbox", "/inbox"],
  ];

  for (const [label, href] of navItems) {
    const re = new RegExp(
      `(<a )href="#"([^>]*>[\\s\\S]*?${label}\\s*</a>)`,
      "i"
    );
    result = result.replace(re, `$1href="${href}" data-pf-link$2`);
  }

  result = result.replace(
    /<a href="#" style="display:flex; align-items:center; gap:7px; font-size:13.5px; font-weight:600; color:#1c1b1a; text-decoration:none;">View full analytics/g,
    '<a href="/dashboard" data-pf-link style="display:flex; align-items:center; gap:7px; font-size:13.5px; font-weight:600; color:#1c1b1a; text-decoration:none;">View full analytics'
  );
  result = result.replace(
    /<a href="#" style="display:flex; align-items:center; gap:7px; font-size:13.5px; font-weight:600; color:#1c1b1a; text-decoration:none;">View all collections/g,
    '<a href="/collections" data-pf-link style="display:flex; align-items:center; gap:7px; font-size:13.5px; font-weight:600; color:#1c1b1a; text-decoration:none;">View all collections'
  );

  return result;
}

function extractFullDashboardBody(html) {
  const start = html.indexOf('<div style="display:flex; min-height:100vh');
  const end = html.indexOf("</x-dc>");
  if (start === -1) return html;
  return html.slice(start, end > start ? end : html.length).trim();
}

function escapeForTemplateLiteral(str) {
  return str.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function main() {
  fs.mkdirSync(DESIGN_DIR, { recursive: true });
  fs.mkdirSync(SECTIONS_DIR, { recursive: true });
  fs.mkdirSync(PUBLIC_DESIGN, { recursive: true });

  if (fs.existsSync(STANDALONE)) {
    fs.copyFileSync(STANDALONE, STANDALONE_COPY);
  }

  const template = extractTemplate();
  const processed = processHtmlIdentical(template);
  const fullBody = extractFullDashboardBody(processed);

  fs.writeFileSync(path.join(DESIGN_DIR, "dashboard.html"), processed);
  fs.writeFileSync(path.join(DESIGN_DIR, "full-dashboard-body.html"), fullBody);

  const styleMatch = template.match(/<style>([\s\S]*?)<\/style>/);
  if (styleMatch) {
    fs.writeFileSync(path.join(DESIGN_DIR, "styles.css"), styleMatch[1]);
  }

  fs.writeFileSync(
    path.join(DESIGN_DIR, "manifest.json"),
    JSON.stringify(
      {
        source: "PetalFlow-Dashboard-standalone.html",
        mode: "identical",
        extractedAt: new Date().toISOString(),
      },
      null,
      2
    )
  );

  const tsFile = `// AUTO-GENERATED by scripts/extract-design.js — do not edit manually
// Source: design/PetalFlow-Dashboard-standalone.html (identical mode)

export const DESIGN_FULL_DASHBOARD_HTML = \`${escapeForTemplateLiteral(fullBody)}\`;

export const DESIGN_STYLES_CSS = \`${escapeForTemplateLiteral(styleMatch?.[1] ?? "")}\`;
`;

  fs.writeFileSync(path.join(ROOT, "lib", "design", "html-sections.ts"), tsFile);

  const previewHtml = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>PetalFlow</title>
<style>${styleMatch?.[1] ?? ""}</style>
</head>
<body>
${fullBody}
</body>
</html>`;
  fs.writeFileSync(path.join(PUBLIC_DESIGN, "preview.html"), previewHtml);
  fs.writeFileSync(path.join(PUBLIC_DESIGN, "index.html"), previewHtml);

  console.log("Design synced (identical mode):");
  console.log(" - design/full-dashboard-body.html");
  console.log(" - lib/design/html-sections.ts");
  console.log(" - public/design/preview.html");
}

main();
